version: "3.8"
services:
  ats_app:
    container_name: ats_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
    depends_on:
      - ats_db
    networks:
      - app_network

  ats_nginx:
    container_name: ats_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - ats_app
    environment:
      NGINX_FPM_HOST: ats_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  ats_db:
    container_name: ats_db
    image: postgres:latest
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    networks:
      - app_network

  ats_redis:
    container_name: ats_redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
